# Project Links
# Made by Sean0402

# Commands

Commands:
  discord:
    Cost: 100
    Delay: 10
    Actions:
      - "[sendMessage] &7Discord link: &cDISCORD.COM"
  twitter:
    Cost: 100
    Delay: 10
    Actions:
      - "[sendMessage] &7Twitter link: &cTWITTER.COM"

Messages:
  onCooldown: "&c&l(!) &fYou are on cooldown for another &c%remaining% seconds&f."
  takenMoney: "&6&l(!) &6%price% &fhas been taken from your balance for running this command!"